pipeline {
    agent any

    environment {
        EMAIL = 'dominhquan15623@example.com'
        DOTNET_CLI_TELEMETRY_OPTOUT = '1'
    }

    stages {
        stage('Restore') {
            steps {
                dir('src/NextHireApp.HttpApi.Host') {
                    bat 'dotnet restore'
                }
            }
        }

        stage('Build') {
            steps {
                dir('src/NextHireApp.HttpApi.Host') {
                    bat 'dotnet build --no-restore -c Release'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('src') {
                    bat 'dotnet test --no-build --logger "trx;LogFileName=test_results.trx" || exit 1'
                }
            }
        }

        stage('Code Analysis') {
            steps {
                dir('src/NextHireApp.HttpApi.Host') {
                    bat 'dotnet format --verify-no-changes || exit 1'
                }
            }
        }

        stage('Deploy to Staging') {
            steps {
                dir('src/NextHireApp.HttpApi.Host') {
                    bat 'dotnet publish -c Release -o out'
                }
            }
        }

        stage('Integration Tests on Staging') {
            steps {
                bat 'echo Running integration tests...'
            }
        }

        stage('Deploy to Production') {
            steps {
                dir('src/NextHireApp.HttpApi.Host') {
                    bat 'dotnet publish -c Release -o out'
                }
            }
        }
    }

    post {
        always {
            mail (
                subject: "Jenkins Pipeline Execution",
                body: "Pipeline execution complete. Check Jenkins for details...",
                to: "${EMAIL}"
            )
        }
    }
}
